spring:
  application:
    name: Architecture # 애플리케이션 이름

  h2:
    console:
      enabled: true # H2 콘솔 활성화
      path: /h2-console # H2 콘솔 접속 경로

  datasource:
    url: jdbc:h2:mem:testdb # H2 메모리 데이터베이스 URL
    driverClassName: org.h2.Driver # H2 드라이버
    username: sa # 기본 사용자 이름
    password: # 비밀번호 없음

  messages:
    basename: message # 메시지 파일의 기본 이름
    encoding: utf-8 # 메시지 파일 인코딩 설정

logging:
  level:
    org.springframework.jdbc.core: debug # JDBC 쿼리 디버그 로그
    org.springframework.jdbc.datasource: debug # 데이터 소스 디버그 로그